apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: customservices.group1.io
  annotations:
          # servicebindingoperator.redhat.io/spec: binding:env:attribute
          # servicebindingoperator.redhat.io/spec.sequence: binding:env:attribute
spec:
        scope: Namespaced
        group: group1.io
        versions:
                - name: v1
                  served: true
                  storage: true
        names:
                kind: CustomService
                singular: customservice
                plural: customservices
