apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: customservices.group1.io
  annotation:
spec:
        scope: Namespaced
        group: group1.io
        versions:
                - name: v1
                  served: true
                  storage: true
        names:
                kind: CustomService
                singular: customservice
                plural: customservices
