apiVersion: postgresql.baiju.dev/v1alpha1
kind: Database
metadata:
  name: db-demo
  namespace: sb-1
spec:
  image: docker.io/postgres
  imageName: postgres
  dbName: db-demo
  slice1:
        - "value1"
        - "value2"
  slice2:
    - subslice1:
        - "value1"
        - 100
  map1:
    key1: "value1"
    key2: "value2"
  sliceOfMap1:
    - key1: "value1"
    - key2: "value2"
