apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: kafka-producer-binding
spec:
  applicationSelector:
    resourceRef: nginx-deployment
    group: apps
    version: v1
    resource: deployments
  backingServiceSelectors:
    - group: kafka.strimzi.io
      kind: Kafka
      resourceRef: my-cluster
      version: v1beta1
        # - group: ''
        #   version: v1
        #   kind: Secret
        #   resourceRef: mysecret
  customEnvVar:
    - name: BOOTSTRAP_SERVERS
      value: |-
        {{- range .status.listeners -}}
          {{- if and (eq .type "tls") (gt (len .addresses) 0) -}}
            {{- with (index .addresses 0) -}}
              {{ .host }}:{{ .port }}
            {{- end -}}
          {{- end -}}
          {{- end -}}
