apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: binding-request
  namespace: sb-1
spec:
  applicationSelector:
    resourceRef: java-rest-http-crud
    group: apps
    version: v1
    resource: deployments
  backingServiceSelectors:
        # - group: ''
        #   version: v1
        #   kind: Secret
        #   resourceRef: mysecret
        - group: postgresql.baiju.dev
          version: v1alpha1
          kind: Database
          resourceRef: db-demo
          id: postgresDB
          # envVarPrefix: DEVTOOLS
  # envVarPrefix: REDHATPROJECT
  customEnvVar:
    - name: JDBC_URL
      value: 'jdbc:postgresql://{{ .postgresDB.status.dbConnectionIP }}:{{ .postgresDB.status.dbConnectionPort }}/{{ .postgresDB.status.dbName }}'
    - name: DB_USER
      value: '{{ .postgresDB.status.dbCredentials.user }}'
    - name: DB_PASSWORD
      value: '{{ .postgresDB.status.dbCredentials.password }}'
    - name: TAGS
      value: '{{ .postgresDB.spec.tags }}'
    # - name: TAGS
    #   value: '{{ .postgresDB.spec.tag }}'
    - name: ARCHIVE_USERLABEL
      value: '{{ .postgresDB.spec.userLabels.archive }}'
    - name: SECONDARY_SECRETNAME
      value: '{{ .postgresDB.spec.secretName }}'

